// ══════════════════════════════════════════════════════════════════
// edge-gateway — Session repository port
//
// The abstract interface for session persistence. The application layer
// depends on this interface, not on any concrete implementation, which is
// the core of hexagonal architecture's dependency inversion.
//
// Implementations: adapters/session-store.pg-repository.ts (PostgreSQL)
// Future: adapters/session-store.redis-repository.ts (Redis)
// ══════════════════════════════════════════════════════════════════

import type { EdgeSession, SessionKind } from '../domain/session.types.js';
import type { Agency } from '@usrp/shared-types';

/**
 * Input for creating a new session. The credential and CSRF token are
 * generated by the store, not supplied by the caller.
 */
export interface CreateSessionInput {
  readonly kind: SessionKind;
  readonly subjectId: string | null;
  readonly agency: Agency | null;
  readonly roles: readonly string[];
  readonly upstreamCredential: string;
  readonly upstreamExpiresAt: string | null;
}

/**
 * Result of creating a session: the full session record plus the two secrets
 * the browser will be handed (handle and CSRF token).
 */
export interface CreateSessionResult {
  readonly session: EdgeSession;
  readonly handle: string;
  readonly csrfToken: string;
}

/**
 * Result of a session lookup by handle: the session is either active, ended
 * (expired/revoked), or unknown (no such handle).
 */
export type SessionLookupResult =
  | { readonly kind: 'ACTIVE'; readonly session: EdgeSession }
  | { readonly kind: 'ENDED'; readonly reason: 'idle' | 'absolute' | 'revoked' }
  | { readonly kind: 'UNKNOWN' };

/**
 * Aggregate session counts for observability. No per-session detail, so this
 * can be emitted to logs without PII concerns.
 */
export interface SessionStats {
  readonly activeOfficer: number;
  readonly activeApplicant: number;
  readonly revoked: number;
  readonly expired: number;
}

/**
 * Session persistence port. The application layer uses this to manage session
 * lifecycle without coupling to PostgreSQL, Redis, or any concrete store.
 *
 * Every operation takes `now: Date` so time-based logic (TTL, expiry) can be
 * tested with a fixed clock, and production can inject `new Date()`.
 */
export interface SessionRepository {
  /**
   * Create a new session. Generates a cryptographically random handle and CSRF
   * token, stores the session with both idle and absolute TTLs, and returns
   * the cleartext secrets (which are hashed in the store).
   *
   * @param input Session attributes
   * @param now Current time (for TTL calculation)
   * @returns The created session plus its handle and CSRF token
   */
  create(input: CreateSessionInput, now: Date): Promise<CreateSessionResult>;

  /**
   * Look up a session by its handle. Returns ACTIVE if the session exists and
   * has not expired; ENDED if it exists but is expired or revoked; UNKNOWN if
   * no such handle.
   *
   * The handle is hashed before lookup, so a cleartext handle from the cookie
   * never appears in a database query log.
   *
   * @param handle Cleartext session handle (from cookie)
   * @param now Current time (for expiry check)
   * @returns Session lookup result
   */
  findByHandle(handle: string, now: Date): Promise<SessionLookupResult>;

  /**
   * Advance the session's idle TTL (lastActivityAt and idleExpiresAt). Called
   * on every authenticated request to keep active sessions alive.
   *
   * @param sessionId The session's database id
   * @param now Current time (new lastActivityAt)
   */
  touch(sessionId: string, now: Date): Promise<void>;

  /**
   * Mark a session as revoked (logout or admin action). The session row stays
   * in the database for audit but will not resolve to ACTIVE anymore.
   *
   * @param sessionId The session's database id
   * @param reason Why the session was revoked (e.g., 'officer_logout')
   * @param now Current time (revokedAt)
   */
  revoke(sessionId: string, reason: string, now: Date): Promise<void>;

  /**
   * Delete expired and revoked session rows older than the grace period. Run
   * periodically (every 15 minutes in production) to keep the table bounded.
   *
   * @param before Delete sessions that expired/revoked before this timestamp
   * @returns Number of rows deleted
   */
  deleteExpired(before: Date): Promise<number>;

  /**
   * Aggregate session counts for the observability line (active officer/
   * applicant, revoked, expired). No per-session detail, so this is safe to
   * log and emit as metrics.
   *
   * @param now Current time (for expiry check)
   * @returns Session counts
   */
  stats(now: Date): Promise<SessionStats>;
}
