// ══════════════════════════════════════════════════════════════════
// edge-gateway — Session repository port
//
// The abstract interface for session persistence. The HTTP adapters and the
// application layer depend on this interface, never on PgEdgeSessionStore.
//
// Implementation: adapters/session-store.pg-repository.ts (PostgreSQL, rls/0019)
// ══════════════════════════════════════════════════════════════════

import type { EdgeSession, SessionKind } from '../domain/session.types.js';
import type { Agency } from '@usrp/shared-types';

/**
 * Input for creating a new session. The handle and CSRF token are generated by
 * the store, not supplied by the caller.
 */
export interface CreateSessionInput {
  readonly kind: SessionKind;
  readonly subjectId: string | null;
  readonly agency: Agency | null;
  readonly roles: readonly string[];
  readonly upstreamCredential: string;
  readonly upstreamExpiresAt: string | null;
}

/** The created session plus the two secrets the browser is handed. */
export interface CreateSessionResult {
  readonly session: EdgeSession;
  readonly handle: string;
  readonly csrfToken: string;
}

/** The outcome of a successful rotation: the new secrets plus the PERSISTED deadlines. */
export interface RotatedSession {
  readonly handle: string;
  readonly csrfToken: string;
  /** As written by the rotating UPDATE (clamped to the absolute ceiling). */
  readonly idleExpiresAt: Date;
  readonly absoluteExpiresAt: Date;
}

/** A lookup is active, ended (with the TRUE reason), or unknown. */
export type SessionLookupResult =
  | { readonly kind: 'ACTIVE'; readonly session: EdgeSession }
  | { readonly kind: 'ENDED'; readonly reason: 'idle' | 'absolute' | 'revoked' }
  | { readonly kind: 'UNKNOWN' };

/** Aggregate counts for observability. No per-session detail. */
export interface SessionStats {
  readonly activeOfficer: number;
  readonly activeApplicant: number;
  readonly revoked: number;
  readonly expired: number;
}

export interface SessionRepository {
  /** Mint a handle and CSRF token, persist their keyed hashes, return the cleartext once. */
  create(input: CreateSessionInput, now: Date): Promise<CreateSessionResult>;

  /**
   * Resolve a CLEARTEXT handle (from the cookie). The store hashes it; the
   * cleartext never appears in a query. Rotated-away handles resolve during
   * the grace window.
   */
  findByHandle(handle: string, now: Date): Promise<SessionLookupResult>;

  /** Advance the sliding idle window (never past the absolute ceiling). */
  touch(sessionId: string, now: Date): Promise<void>;

  /**
   * Rotate BOTH secrets and advance the idle window. The previous pair stays
   * valid for a short grace window for in-flight requests.
   *
   * Returns null when no live row was rotated (the session was revoked between
   * resolve and rotate). Handing back a handle that was never stored would set
   * a cookie that can only ever 401.
   */
  rotate(sessionId: string, now: Date): Promise<RotatedSession | null>;

  /** Idempotent revoke. The sealed upstream credential is blanked, not just flagged. */
  revoke(sessionId: string, reason: string, now: Date): Promise<void>;

  /** Delete rows past every deadline. Returns rows deleted. */
  deleteExpired(before: Date): Promise<number>;

  stats(now: Date): Promise<SessionStats>;
}
