import {useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import "./styles.css";
type Agency="RDF"|"RNP"|"RCS"; type Session={kind:"officer";agency:Agency;roles:string[];idleExpiresAt:string;absoluteExpiresAt:string};
type Row={applicationId:string|null;processingCode:string|null;category:string|null;status:string|null;agency:Agency;submittedAt:string|null}; type Detail={application:any;history:any[]};
const HERO="https://www.mod.gov.rw/fileadmin/user_upload/RDF/News_images/30_JULY_2026_B/3.jpg";
const nav=[["Overview","overview","⌂"],["Applications","applications","▤"],["Amber Queue","amber","⚠"],["Walk-in Registration","walkin","♙"],["Identity Verification","identity","◈"],["Physical Testing","field","↗"],["Medical Review","medical","✚"],["Final Decision","decision","✓"],["Field Sync","sync","↻"],["Reports","reports","▥"]];
function cookie(n:string){return document.cookie.split("; ").find(x=>x.startsWith(n+"="))?.split("=").slice(1).join("=")||null}
function csrf(){return cookie("__Host-usrp_csrf")||cookie("usrp_csrf_dev")}
async function api<T>(path:string,init:RequestInit={},need=false):Promise<T>{const h=new Headers(init.headers);h.set("Accept","application/json");if(init.body)h.set("Content-Type","application/json");if(need){const c=csrf();if(c)h.set("x-csrf-token",c)}const r=await fetch(path,{...init,headers:h,credentials:"include"});if(r.status===204)return undefined as T;const t=await r.text();let b:any;try{b=t?JSON.parse(t):undefined}catch{b=t}if(!r.ok)throw new Error(b?.error||"Request failed ("+r.status+")");return b as T}
const label=(v:any)=>String(v==null?"UNKNOWN":v).replaceAll("_"," "); const date=(v:any)=>v?new Date(v).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"}):"—";
const tone=(v:any)=>/REJECT|UNFIT/.test(String(v))?"danger":/AMBER|MEDICAL|PENDING|VETTING|CLEARANCE/.test(String(v))?"warning":/ACCEPTED|SHORTLIST|COMPLETE|FIT|CLEARED/.test(String(v))?"success":"info";
const agencyName=(a:Agency)=>a==="RDF"?"Rwanda Defence Force":a==="RNP"?"Rwanda National Police":"Rwanda Correctional Service";
function Badge({v}:{v:any}){return <span className={"badge "+tone(v)}>{label(v)}</span>}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="card"><h3>{title}</h3>{children}</section>}
function Login({done,error}:{done:()=>void;error:string}){const [u,setU]=useState(""),[p,setP]=useState(""),[busy,setBusy]=useState(false);async function go(e:React.FormEvent){e.preventDefault();setBusy(true);try{await api("/edge/v1/auth/officer/login",{method:"POST",body:JSON.stringify({loginHandle:u,password:p})},true);done()}catch(x){alert(x instanceof Error?x.message:"Login failed")}finally{setBusy(false)}}return <div className="login"><div className="loginVisual"><img src={HERO}/><div className="shade"/><div className="visualCopy"><small>UNIFIED SECURITY RECRUITMENT PORTAL</small><h1>Recruitment Operations Console</h1><p>Secure officer operations for Rwanda Defence Force, Rwanda National Police and Rwanda Correctional Service.</p></div></div><form onSubmit={go}><div className="crest">★</div><small className="eyebrow">OFFICER ACCESS</small><h2>Sign in</h2><p>Use authorized officer credentials. Agency is established by the verified session.</p>{error&&<div className="alert danger">{error}</div>}<label>Login handle<input value={u} onChange={e=>setU(e.target.value)} required/></label><label>Password<input type="password" value={p} onChange={e=>setP(e.target.value)} required/></label><button className="primary">{busy?"Signing in…":"Sign in securely"}</button><small className="muted">The browser never receives the officer JWT. Session state uses secure cookies.</small></form></div>}
function App(){const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[rows,setRows]=useState<Row[]>([]),[amber,setAmber]=useState<any[]>([]),[page,setPage]=useState("overview"),[q,setQ]=useState(""),[selected,setSelected]=useState<Detail|null>(null),[status,setStatus]=useState("ALL"),[busy,setBusy]=useState(false);
async function probe(){try{const s:any=await api("/edge/v1/session");setSession(s?.kind==="officer"?s:null);setError("")}catch(e){setError(e instanceof Error?e.message:"Edge Gateway unavailable")}finally{setLoading(false)}}
async function refresh(){if(!session)return;setBusy(true);try{const a:any=await api("/edge/v1/applications"),b:any=await api("/edge/v1/applications/amber-queue");setRows(Array.isArray(a)?a:[]);setAmber(Array.isArray(b)?b:[])}catch(e){setError(e instanceof Error?e.message:"Unable to load applications")}finally{setBusy(false)}}
useEffect(()=>{probe()},[]);useEffect(()=>{refresh()},[session]);
const filtered=useMemo(()=>rows.filter(x=>(!q||(String(x.processingCode)+" "+String(x.category)+" "+String(x.status)).toLowerCase().includes(q.toLowerCase()))&&(status==="ALL"||x.status===status)),[rows,q,status]);
async function open(id:string){try{setSelected(await api<Detail>("/edge/v1/applications/detail?applicationId="+encodeURIComponent(id)))}catch(e){setError(e instanceof Error?e.message:"Unable to open application")}}
async function logout(){await api("/edge/v1/auth/officer/logout",{method:"POST"},true);setSession(null);setRows([]);setAmber([])}
if(loading)return <div className="boot">Loading secure USRP session…</div>; if(!session)return <Login done={probe} error={error}/>;
const medical=rows.filter(x=>x.status==="MEDICAL_REVIEW").length,shortlist=rows.filter(x=>x.status==="FINAL_SHORTLIST").length;
return <div className="app"><aside className="sidebar"><div className="brand"><span className="crest">★</span><div><b>Unified Security<br/>Recruitment Portal</b><small>RDF · RNP · RCS</small></div></div><nav>{nav.map(([n,id,icon])=><button key={id} className={page===id?"active":""} onClick={()=>setPage(id)}><i>{icon}</i><span>{n}</span>{id==="amber"&&amber.length>0&&<em>{amber.length}</em>}</button>)}</nav><div className="agencyBox"><small>AUTHORIZED AGENCY</small><strong>{session.agency}</strong><span>{agencyName(session.agency)}</span></div><div className="operator"><span>RO</span><div><b>{session.agency} Officer</b><small>Recruitment Operations</small></div><button onClick={logout}>Sign out</button></div></aside>
<main className="main"><header className="top"><div className="search">⌕<input placeholder="Search application or processing code…" value={q} onChange={e=>setQ(e.target.value)}/></div><div><b>{session.agency} Officer</b><small>{agencyName(session.agency)}</small></div></header><div className="content">{error&&<div className="alert danger">{error}</div>}
<section className="hero"><img src={HERO}/><div className="shade"/><div className="heroText"><small>USRP / {session.agency} / RECRUITMENT OPERATIONS</small><h1>Recruitment Operations</h1><p>{agencyName(session.agency)}</p><span>Agency-scoped operational recruitment processing</span></div></section>
<div className="pageHead"><div><h2>{label(page)}</h2><small>Live data from the Edge Gateway. No invented aggregate endpoints.</small></div><button onClick={refresh}>{busy?"Refreshing…":"↻ Refresh"}</button></div>
{page==="overview"&&<><div className="kpis"><K title="Visible applications" v={rows.length} n="Current officer scope"/><K title="Amber queue" v={amber.length} n="Document review"/><K title="Medical review" v={medical} n="Current pipeline"/><K title="Final shortlist" v={shortlist} n="Awaiting decision"/></div><div className="grid2"><Card title="Recruitment pipeline">{["SUBMITTED","ACADEMIC_VETTING","CRIMINAL_CLEARANCE","DOCUMENT_REVIEW_AMBER","PHYSICAL_TEST_COMPLETE","MEDICAL_REVIEW","FINAL_SHORTLIST","ACCEPTED"].map(s=><div className="pipeline" key={s}><span>{label(s)}</span><div><i style={{width:(rows.length?Math.max(rows.filter(x=>x.status===s).length?5:0,rows.filter(x=>x.status===s).length/rows.length*100):0)+"%"}}/></div><b>{rows.filter(x=>x.status===s).length}</b></div>)}</Card><Card title="Operational summary"><Summary n={rows.filter(x=>x.status==="ACCEPTED"||x.status==="REJECTED").length} t="Completed decisions"/><Summary n={amber.length} t="Documents requiring review"/><Summary n={medical} t="Applications in medical review"/><Summary n={shortlist} t="At final shortlist"/></Card></div></>}
{(page==="overview"||page==="applications"||page==="amber")&&<Card title={page==="amber"?"Amber review queue":"Applications"}><div className="filters">{page!=="amber"&&<select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option>{Array.from(new Set(rows.map(x=>x.status).filter(Boolean))).map(s=><option key={String(s)}>{s}</option>)}</select>}</div><table><thead><tr><th>Processing code</th><th>Category</th><th>Status</th><th>Agency</th><th>Date</th><th/></tr></thead><tbody>{(page==="amber"?amber:filtered).map((x:any,i:number)=><tr key={x.applicationId||i}><td><button className="link" onClick={()=>x.applicationId&&open(x.applicationId)}>{x.processingCode||"—"}</button></td><td>{label(x.category||x.documentType)}</td><td><Badge v={x.status}/></td><td>{x.agency}</td><td>{date(x.submittedAt||x.queuedAt)}</td><td>{x.applicationId&&<button className="link" onClick={()=>open(x.applicationId)}>Open →</button>}</td></tr>)}{(page==="amber"?amber:filtered).length===0&&<tr><td colSpan={6} className="empty">No records in this view.</td></tr>}</tbody></table></Card>}
{["walkin","identity","field","medical","decision","sync","reports"].includes(page)&&<Card title={label(page)}><div className="capability"><strong>Backend capability reserved for this surface.</strong><p>The current Edge Gateway exposes operations here, but the browser contract does not provide a matching read model for this page yet. We will not invent data or controls.</p><code>/edge/v1/{page==="medical"?"applications/medical-review":page==="decision"?"applications/final-decision":page}</code></div></Card>}</div></main>{selected&&<Drawer data={selected} close={()=>setSelected(null)} reload={refresh}/>}</div>}
}
function K({title,v,n}:{title:string;v:number;n:string}){return <div className="kpi"><span>●</span><div><small>{title}</small><strong>{v}</strong><em>{n}</em></div></div>}
function Summary({n,t}:{n:number;t:string}){return <div className="summary"><b>{n}</b><span>{t}</span></div>}
function Drawer({data,close,reload}:{data:Detail;close:()=>void;reload:()=>void}){const a=data.application;async function medical(ok:boolean){const body=a.agency==="RDF"?{applicationId:a.applicationId,fitnessStatus:ok?"FIT":"UNFIT"}:{applicationId:a.applicationId,certVerdict:ok?"CERT_VERIFIED":"CERT_REJECTED"};await api("/edge/v1/applications/medical-review",{method:"POST",body:JSON.stringify(body)},true);close();reload()}async function accept(){await api("/edge/v1/applications/accept",{method:"POST",body:JSON.stringify({applicationId:a.applicationId})},true);close();reload()}return <div className="drawerBack" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><header><div><small>APPLICATION DETAIL</small><h2>{a.processingCode||a.applicationId}</h2></div><button onClick={close}>×</button></header><div className="drawerBody"><Badge v={a.status}/><Card title="Application"><Info n="Agency" v={a.agency}/><Info n="Category" v={label(a.category)}/><Info n="Academic status" v={label(a.academicStatus)}/><Info n="Age eligibility" v={label(a.ageEligibilityStatus)}/><Info n="Criminal clearance" v={label(a.criminalClearanceStatus)}/><Info n="District" v={a.assignedDistrict}/><Info n="Venue" v={a.assignedVenueName}/></Card><Card title="Recruitment checks">{[["Academic vetting",a.academicStatus],["Age eligibility",a.ageEligibilityStatus],["Criminal clearance",a.criminalClearanceStatus],["Physical test",a.physicalTestCompletedAt?"COMPLETE":a.physicalTestScheduledAt?"SCHEDULED":"PENDING"],["Medical review",a.status==="MEDICAL_REVIEW"?"IN PROGRESS":a.finalDecisionAt?"COMPLETED":"PENDING"],["Final decision",a.finalDecisionAt?"COMPLETED":"PENDING"]].map((x:any)=><div className="check" key={x[0]}><b>✓</b><div><strong>{x[0]}</strong><small>{label(x[1])}</small></div></div>)}</Card>{a.documentForensicsScore!=null&&<Card title="Document review signals"><strong className="score">{a.documentForensicsScore}</strong><small className="muted">Officer-only forensic signal</small></Card>}<Card title="Decision history">{data.history?.map((h:any,i:number)=><div className="history" key={h.entryId||i}><b>{label(h.toStatus)}</b><small>{date(h.occurredAt)} · {h.actorKind||"SYSTEM"}</small>{h.note&&<p>{h.note}</p>}</div>)}</Card><div className="actions">{a.status==="MEDICAL_REVIEW"&&<><button className="ok" onClick={()=>medical(true)}>✓ Fit / verified</button><button className="dangerBtn" onClick={()=>medical(false)}>✕ Unfit / rejected</button></>}{a.status==="FINAL_SHORTLIST"&&<button className="primary" onClick={accept}>Accept application</button>}</div></div></aside></div>}
function Info({n,v}:{n:string;v:any}){return <div className="info"><span>{n}</span><b>{v||"—"}</b></div>}
createRoot(document.getElementById("root")!).render(<App/>);