const root=document.getElementById("root"),HERO="https://www.mod.gov.rw/fileadmin/user_upload/RDF/News_images/30_JULY_2026_B/3.jpg";
const nav=[["Overview","overview","⌂"],["Applications","applications","▤"],["Amber Queue","amber","⚠"],["Walk-in Registration","walkin","♙"],["Identity Verification","identity","◈"],["Physical Testing","field","↗"],["Medical Review","medical","✚"],["Final Decision","decision","✓"],["Field Sync","sync","↻"],["Reports","reports","▥"]];
const S={page:"overview",q:"",status:"ALL",session:null,rows:[],amber:[],error:""};
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),lab=x=>String(x??"UNKNOWN").replaceAll("_"," "),dt=x=>x?new Date(x).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"}):"—";
const tone=x=>/REJECT|UNFIT/.test(String(x))?"danger":/AMBER|MEDICAL|PENDING|VETTING|CLEARANCE/.test(String(x))?"warning":/ACCEPTED|SHORTLIST|COMPLETE|FIT|CLEARED/.test(String(x))?"success":"info";
const badge=x=>'<span class="badge '+tone(x)+'">'+esc(lab(x))+"</span>";
function ck(n){const x=document.cookie.split("; ").find(v=>v.startsWith(n+"="));return x?decodeURIComponent(x.slice(n.length+1)):null}
async function api(path,opt={},csrf=false){const h=new Headers(opt.headers);h.set("Accept","application/json");if(opt.body)h.set("Content-Type","application/json");if(csrf){const c=ck("__Host-usrp_csrf")||ck("usrp_csrf_dev");if(c)h.set("x-csrf-token",c)}const r=await fetch(path,{...opt,headers:h,credentials:"include"});if(r.status===204)return;const t=await r.text();let b;try{b=t?JSON.parse(t):null}catch{b=t}if(!r.ok)throw Error(b?.error||"Request failed ("+r.status+")");return b}
function login(){root.innerHTML='<div class="login"><div class="loginVisual"><img src="'+HERO+'"><div class="shade"></div><div class="visualCopy"><small>UNIFIED SECURITY RECRUITMENT PORTAL</small><h1>Recruitment Operations Console</h1><p>Secure officer operations for RDF, RNP and RCS.</p></div></div><form id="lf"><div class="crest">★</div><small class="eyebrow">OFFICER ACCESS</small><h2>Sign in</h2><p>Agency is established by the verified officer session.</p><div id="le"></div><label>Login handle<input name="u" required></label><label>Password<input name="p" type="password" required></label><button class="primary">Sign in securely</button><small class="muted">The browser never receives the officer JWT.</small></form></div>';lf.onsubmit=async e=>{e.preventDefault();const f=new FormData(lf);try{await api("/edge/v1/auth/officer/login",{method:"POST",body:JSON.stringify({loginHandle:f.get("u"),password:f.get("p")})},true);boot()}catch(x){le.innerHTML='<div class="alert danger">'+esc(x.message)+"</div>"}}}
async function boot(){try{const s=await api("/edge/v1/session");if(s?.kind==="officer"){S.session=s;await refresh()}else{login();return}}catch(x){S.error=x.message;login();return}render()}
async function refresh(){if(!S.session)return;try{const a=await api("/edge/v1/applications"),b=await api("/edge/v1/applications/amber-queue");S.rows=Array.isArray(a)?a:[];S.amber=Array.isArray(b)?b:[];S.error=""}catch(x){S.error=x.message}render()}
function list(){return S.page==="amber"?S.amber:S.rows.filter(x=>(!S.q||(String(x.processingCode)+" "+String(x.category)+" "+String(x.status)).toLowerCase().includes(S.q.toLowerCase()))&&(S.status==="ALL"||x.status===S.status))}
function k(t,v,n){return '<div class="kpi"><span>●</span><div><small>'+t+'</small><strong>'+v+'</strong><em>'+n+"</em></div></div>"}
function table(a){return '<table><thead><tr><th>Processing code</th><th>Category</th><th>Status</th><th>Agency</th><th>Date</th><th></th></tr></thead><tbody>'+a.map(x=>'<tr><td><button class="link" data-id="'+esc(x.applicationId)+'">'+esc(x.processingCode||"—")+'</button></td><td>'+esc(lab(x.category||x.documentType))+'</td><td>'+badge(x.status)+'</td><td>'+esc(x.agency)+'</td><td>'+dt(x.submittedAt||x.queuedAt)+'</td><td><button class="link" data-id="'+esc(x.applicationId)+'">Open →</button></td></tr>').join("")+(a.length?"":'<tr><td colspan="6" class="empty">No records in this view.</td></tr>')+"</tbody></table>"}
function content(a){const m=S.rows.filter(x=>x.status==="MEDICAL_REVIEW").length,f=S.rows.filter(x=>x.status==="FINAL_SHORTLIST").length;if(S.page==="overview")return '<div class="kpis">'+k("Visible applications",S.rows.length,"Current officer scope")+k("Amber queue",S.amber.length,"Document review")+k("Medical review",m,"Current pipeline")+k("Final shortlist",f,"Awaiting decision")+'</div><div class="grid2"><section class="card"><h3>Recruitment pipeline</h3>'+["SUBMITTED","ACADEMIC_VETTING","CRIMINAL_CLEARANCE","DOCUMENT_REVIEW_AMBER","PHYSICAL_TEST_COMPLETE","MEDICAL_REVIEW","FINAL_SHORTLIST","ACCEPTED"].map(x=>{const n=S.rows.filter(r=>r.status===x).length;return '<div class="pipeline"><span>'+lab(x)+'</span><div><i style="width:'+(S.rows.length?Math.max(n?5:0,n/S.rows.length*100):0)+'%"></i></div><b>'+n+"</b></div>"}).join("")+'</section><section class="card"><h3>Operational summary</h3><div class="summary"><b>'+S.amber.length+'</b><span>Documents requiring review</span></div><div class="summary"><b>'+m+'</b><span>Applications in medical review</span></div><div class="summary"><b>'+f+'</b><span>At final shortlist</span></div></section></div>'+table(a);
if(S.page==="applications"||S.page==="amber")return '<section class="card"><h3>'+lab(S.page==="amber"?"Amber review queue":"Applications")+'</h3><div class="filters">'+(S.page==="applications"?'<select id="st"><option value="ALL">All statuses</option>'+Array.from(new Set(S.rows.map(x=>x.status).filter(Boolean))).map(x=>'<option>'+x+"</option>").join("")+"</select>":"")+"</div>"+table(a)+"</section>";
return '<section class="card"><h3>'+lab(S.page)+'</h3><div class="capability"><strong>Backend capability reserved for this surface.</strong><p>The Edge Gateway exposes operations here, but the current browser contract does not provide a matching read model yet. We will not invent data or controls.</p></div></section>"}
function render(){if(!S.session)return;const s=S.session;root.innerHTML='<div class="app"><aside class="sidebar"><div class="brand"><span class="crest">★</span><div><b>Unified Security<br>Recruitment Portal</b><small>RDF · RNP · RCS</small></div></div><nav>'+nav.map(x=>'<button class="'+(S.page===x[1]?"active":"")+'" data-p="'+x[1]+'"><i>'+x[2]+'</i><span>'+x[0]+'</span>'+(x[1]==="amber"&&S.amber.length?'<em>'+S.amber.length+"</em>":"")+"</button>").join("")+'</nav><div class="agencyBox"><small>AUTHORIZED AGENCY</small><strong>'+s.agency+'</strong><span>'+esc(s.agency==="RDF"?"Rwanda Defence Force":s.agency==="RNP"?"Rwanda National Police":"Rwanda Correctional Service")+'</span></div><div class="operator"><span>RO</span><div><b>'+s.agency+" Officer</b><small>Recruitment Operations</small></div><button id="out">Sign out</button></div></aside><main class="main"><header class="top"><div class="search">⌕<input id="q" placeholder="Search application or processing code…" value="'+esc(S.q)+'"></div><div><b>'+s.agency+" Officer</b><small>"+esc(s.agency==="RDF"?"Rwanda Defence Force":s.agency==="RNP"?"Rwanda National Police":"Rwanda Correctional Service")+"</small></div></header><div class="content">"+(S.error?'<div class="alert danger">'+esc(S.error)+"</div>":"")+'<section class="hero"><img src="'+HERO+'"><div class="shade"></div><div class="heroText"><small>USRP / '+s.agency+" / RECRUITMENT OPERATIONS</small><h1>Recruitment Operations</h1><p>"+esc(s.agency==="RDF"?"Rwanda Defence Force":s.agency==="RNP"?"Rwanda National Police":"Rwanda Correctional Service")+'</p><span>Agency-scoped operational recruitment processing</span></div></section><div class="pageHead"><div><h2>'+lab(S.page)+'</h2><small>Live data from the Edge Gateway. No invented aggregate endpoints.</small></div><button id="ref">↻ Refresh</button></div>'+content(list())+"</div></main></div>";
document.querySelectorAll("[data-p]").forEach(b=>b.onclick=()=>{S.page=b.dataset.p;render()});q.oninput=e=>{S.q=e.target.value;render()};ref.onclick=refresh;out.onclick=async()=>{await api("/edge/v1/auth/officer/logout",{method:"POST"},true);S.session=null;login()};document.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>open(b.dataset.id));const st=document.getElementById("st");if(st)st.onchange=e=>{S.status=e.target.value;render()}}
async function open(id){try{const d=await api("/edge/v1/applications/detail?applicationId="+encodeURIComponent(id));drawer(d)}catch(x){S.error=x.message;render()}}
function info(n,v){return '<div class="info"><span>'+n+'</span><b>'+esc(v||"—")+"</b></div>"}
function drawer(d){const a=d.application;root.insertAdjacentHTML("beforeend",'<div class="drawerBack" id="db"><aside class="drawer"><header><div><small>APPLICATION DETAIL</small><h2>'+esc(a.processingCode||a.applicationId)+'</h2></div><button id="dc">×</button></header><div class="drawerBody">'+badge(a.status)+'<section class="card"><h3>Application</h3>'+info("Agency",a.agency)+info("Category",lab(a.category))+info("Academic status",lab(a.academicStatus))+info("Age eligibility",lab(a.ageEligibilityStatus))+info("Criminal clearance",lab(a.criminalClearanceStatus))+info("District",a.assignedDistrict)+info("Venue",a.assignedVenueName)+'</section><section class="card"><h3>Recruitment checks</h3>'+[["Academic vetting",a.academicStatus],["Age eligibility",a.ageEligibilityStatus],["Criminal clearance",a.criminalClearanceStatus],["Physical test",a.physicalTestCompletedAt?"COMPLETE":a.physicalTestScheduledAt?"SCHEDULED":"PENDING"],["Medical review",a.status==="MEDICAL_REVIEW"?"IN PROGRESS":a.finalDecisionAt?"COMPLETED":"PENDING"],["Final decision",a.finalDecisionAt?"COMPLETED":"PENDING"]].map(x=>'<div class="check"><b>✓</b><div><strong>'+x[0]+'</strong><small>'+lab(x[1])+"</small></div></div>").join("")+"</section>"+(a.documentForensicsScore!=null?'<section class="card"><h3>Document review signals</h3><strong class="score">'+a.documentForensicsScore+'</strong><small class="muted">Officer-only forensic signal</small></section>':"")+'<section class="card"><h3>Decision history</h3>'+((d.history||[]).map(h=>'<div class="history"><b>'+lab(h.toStatus)+'</b><small>'+dt(h.occurredAt)+" · "+esc(h.actorKind||"SYSTEM")+"</small>"+(h.note?"<p>"+esc(h.note)+"</p>":"")+"</div>").join("")||'<div class="empty">No status history returned.</div>')+'</section><div class="actions">'+(a.status==="MEDICAL_REVIEW"?'<button class="ok" id="fit">✓ Fit / verified</button><button class="dangerBtn" id="unfit">✕ Unfit / rejected</button>':"")+(a.status==="FINAL_SHORTLIST"?'<button class="primary" id="acc">Accept application</button>':"")+"</div></div></aside></div>");dc.onclick=()=>db.remove();db.onclick=e=>{if(e.target===db)db.remove()};if(fit)fit.onclick=()=>medical(a,true);if(unfit)unfit.onclick=()=>medical(a,false);if(acc)acc.onclick=()=>acceptApp(a)}
async function medical(a,ok){const body=a.agency==="RDF"?{applicationId:a.applicationId,fitnessStatus:ok?"FIT":"UNFIT"}:{applicationId:a.applicationId,certVerdict:ok?"CERT_VERIFIED":"CERT_REJECTED"};await api("/edge/v1/applications/medical-review",{method:"POST",body:JSON.stringify(body)},true);db.remove();refresh()}
async function acceptApp(a){await api("/edge/v1/applications/accept",{method:"POST",body:JSON.stringify({applicationId:a.applicationId})},true);db.remove();refresh()}
boot();